version: "3"

services:
  dashboard-app:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - 3000:3000

  transcription-service:
    build:
      context: .
      dockerfile: services/transcription-service/Dockerfile
    ports:
      - 4002:4000

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - 4001:4000

  transcription-db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcription
    ports:
      - 5432:5432
    volumes:
      - transcription-db:/var/lib/postgresql/data

volumes:
  transcription-db:
