version: "3"

services:
  dashboard-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    ports:
      - 3000:3000

  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: transcription-service
    ports:
      - 4002:4000

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    ports:
      - 4001:4000

  transcription-db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcription
    ports:
      - 5432:5432
    volumes:
      - transcription-db:/var/lib/postgresql/data

  redis:
    image: redis:6.0.1-alpine
    ports:
      - 6379:6379

volumes:
  transcription-db:
