version: "3"

services:
  dashboard-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    ports:
      - 3000:3000
  transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: transcription-service
    ports:
      - 4002:4000
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    ports:
      - 4001:4000
