federation_version: 2
sandbox:
  enabled: true
subgraphs:
  users:
    routing_url: http://127.0.0.1:4001/graphql
    schema:
      subgraph_url: http://127.0.0.1:4001/graphql
  transcriptions:
    routing_url: http://127.0.0.1:4002/graphql
    schema:
      subgraph_url: http://127.0.0.1:4002/graphql


# federation_version: 2
# sandbox:
#   enabled: true
# subgraphs:
#   users:
#     routing_url: http://34.140.139.18:80/graphql
#     schema:
#       subgraph_url: http://127.0.0.1:4001/graphql
#   transcriptions:
#     routing_url: http://34.76.162.125:80/graphql
#     schema:
#       subgraph_url: http://127.0.0.1:4002/graphql