apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: transcription-service-hpa
  namespace: ml-saas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transcription-service-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
