apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-saas-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mlsaas.ryanis.moe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80
    - host: user.ryanis.moe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
    - host: transcription.ryanis.moe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transcription-service
                port:
                  number: 80
