apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-saas-ingress
  namespace: ml-saas
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ml-saas-ip
    networking.gke.io/managed-certificates: ml-saas-certificate
    networking.gke.io/v1beta1.FrontendConfig: ingress-security-config
    ingressClassName: "gce"
spec:
  rules:
    - host: dashboard.ryanis.moe
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: dashboard
                port:
                  number: 80
    - host: user.ryanis.moe
      http:
        paths:
          - pathType: Prefix
            path: "/graphql"
            backend:
              service:
                name: user-service
                port:
                  number: 80
    - host: transcription.ryanis.moe
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: transcription-service
                port:
                  number: 80
