apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: ml-saas
spec:
  type: LoadBalancer
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ml-saas
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: transcription-service
  namespace: ml-saas
spec:
  type: LoadBalancer
  selector:
    app: transcription-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4002
