name: Docker Image CD - user-service

env:
  SERVICE_NAME: user-service

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "services/user-service/**"
  pull_request:
    branches: ["main"]

jobs:
  testing:
    uses: ./.github/workflows/ci.yaml

  build:
    runs-on: ubuntu-latest
    needs: testing

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx build --push --target ${{env.SERVICE_NAME}} --tag ${{vars.REGISTRY}}/ml-saas/${{env.SERVICE_NAME}}:latest --platform ${{vars.PLATFORMS}} .
