name: Docker Image CD - transcription-service

env:
  SERVICE_NAME: transcription-service

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "services/transcription-service/**"
  pull_request:
    branches: ["main"]
    paths:
      - "services/transcription-service/**"

jobs:
  testing:
    uses: ./.github/workflows/ci.yaml

  build:
    name: Build Docker image and push to registry
    runs-on: ubuntu-latest
    needs: testing

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker buildx create --use
          docker buildx build --push -f ./services/transcription-service/Dockerfile --tag ${{vars.REGISTRY}}/ml-saas/${{env.SERVICE_NAME}}:latest --platform ${{vars.PLATFORMS}} ./services/${{env.SERVICE_NAME}} .
